Repository CA-G12/e-commerce-team8, pull requests merged in 2022-09, with the labels that each got.

#2 finished project setup
  .eslintrc.json
  .gitignore
  README.md
  build.js
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/App.test.js
  client/src/components/card/Card.css
  client/src/components/card/Card.js
  client/src/components/cart/Cart.css
  client/src/components/cart/Cart.js
  client/src/components/landing-page/Landing.css
  client/src/components/landing-page/Landing.js
  client/src/components/navbar/Navbar.css
  client/src/components/navbar/Navbar.js
  client/src/components/product/Product.css
  client/src/components/product/Product.js
  client/src/components/sign-in/Sign-in.css
  client/src/components/sign-in/Sign-in.js
  client/src/components/sign-up/Sign-up.css
  client/src/components/sign-up/Sign-up.js
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  example.env
  package-lock.json
  package.json
  server/app.js
  server/controllers/authController.js
  server/controllers/index.js
  server/controllers/userController.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/queries/index.js
  server/database/queries/products/buyProductQuery.js
  server/database/queries/products/deleteProductQuery.js
  server/database/queries/products/getAllProductsQuery.js
  server/database/queries/products/getCartProductsQuery.js
  server/database/queries/products/index.js
  server/database/queries/register/checkEmailQuery.js
  server/database/queries/register/index.js
  server/database/queries/register/signInQuery.js
  server/database/queries/register/signUpQuery.js
  server/middlewares/index.js
  server/middlewares/verifyToken.js
  server/routes/index.js
  server/routes/products.js
  server/routes/register.js
  server/server.js
  server/tests/database.test.js
  server/tests/routes.test.js
  server/utils/customError.js
  server/utils/tokenPromise.js
Labels: for-review

#3 Modify eslint
  .eslintrc.json
  README.md
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  package.json
  server/app.js
  server/server.js
  server/validation/index.js
  server/validation/signInValidation.js
  server/validation/signUpValidation.js
Labels: for-review

#6 added the imageurl in build.sql file
  server/database/config/build.sql
Labels: approved

#7 fixed the server side eslint
  .eslintrc.json
  client/package.json
  package-lock.json
  package.json
Labels: approved

#12 created the check email query
  server/controllers/authController.js
  server/controllers/index.js
  server/controllers/register/index.js
  server/controllers/register/signUp.js
  server/controllers/userController.js
  server/database/queries/register/checkEmailQuery.js
  server/routes/register.js
Labels: for-review, approved

#10 build: Authentication - verify token - middleware
  server/middlewares/verifyToken.js
Labels: for-review

#14 created the sign up in server side which includes input verfication a…
  server/app.js
  server/controllers/register/signUp.js
  server/database/queries/register/signUpQuery.js
  server/routes/register.js
Labels: approved

#15 write: require & export in index file
  server/middlewares/index.js
  server/middlewares/verifyToken.js
Labels: approved

#16 4 backend build sign in functionality
  .gitignore
  .vscode/settings.json
  server/controllers/index.js
  server/controllers/products/index.js
  server/controllers/register/index.js
  server/controllers/register/signIn.js
  server/database/config/build.sql
  server/database/queries/register/index.js
  server/database/queries/register/signInQuery.js
  server/routes/register.js
Labels: for-review

#19 Write get all products query and its controller
  server/controllers/index.js
  server/controllers/products/getAll.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/getAllProductsQuery.js
  server/routes/index.js
  server/routes/products.js
Labels: approved

#22 20 create cart server
  server/controllers/index.js
  server/controllers/products/getCartProducts.js
  server/controllers/products/index.js
  server/controllers/register/signUp.js
  server/database/queries/products/getCartProductsQuery.js
  server/middlewares/index.js
  server/routes/products.js
Labels: approved

#24 18 add to cart feature server side
  server/controllers/index.js
  server/controllers/products/buyProduct.js
  server/controllers/products/index.js
  server/database/queries/products/buyProductQuery.js
  server/middlewares/index.js
  server/routes/products.js
  server/utils/tokenPromise.js
Labels: done

#23 delete query relates #21
  server/controllers/index.js
  server/controllers/products/delete.js
  server/controllers/products/index.js
  server/database/queries/products/deleteProductQuery.js
  server/routes/products.js
Labels: approved

#25 adding product relates #5
  server/database/config/productBuild.js
  server/database/config/products.js
Labels: approved

#30 build: log out feature
  server/controllers/index.js
  server/controllers/register/index.js
  server/controllers/register/signOut.js
  server/routes/register.js
Labels: approved

#33 created the sign up in client side
  client/src/components/sign-up/Sign-up.css
  client/src/components/sign-up/Sign-up.js
Labels: approved

#35 build: functions for getting product by ID
  server/controllers/index.js
  server/controllers/products/getProduct.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/getProductQuery.js
  server/database/queries/products/index.js
  server/routes/products.js
Labels: approved

#36 handle the landing page and display cards relates #34
  client/package-lock.json
  client/src/components/card/Card.css
  client/src/components/card/Card.js
  client/src/components/cardsContainer/CardsContainer.css
  client/src/components/cardsContainer/CardsContainer.js
Labels: approved

#37 32 react create sign in client side
  client/src/components/index.js
  client/src/components/sign-in/Sign-in.css
  client/src/components/sign-in/Sign-in.js
  client/src/components/sign-up/Sign-up.js
Labels: approved

#39 38 modify backend modify gatall and signin files
  server/controllers/products/getAll.js
  server/controllers/register/signIn.js
  server/server.js
Labels: approved

#41 categories relates #40
  client/package.json
  client/src/components/cardsContainer/CardsContainer.js
  client/src/components/categories/Categories.js
  client/src/components/landing-page/Landing.js
Labels: approved

#44 Build: cart & cart-Item component without style
  client/src/components/cart/Cart.css
  client/src/components/cart/Cart.js
  client/src/components/cartItem/CartItem.css
  client/src/components/cartItem/CartItem.js
  server/controllers/register/signOut.js
Labels: approved

#48 add card style and categories style and started with Pagination relat…
  client/src/components/card/Card.css
  client/src/components/card/Card.js
  client/src/components/cardsContainer/CardsContainer.css
  client/src/components/cardsContainer/CardsContainer.js
  client/src/components/categories/Categories.css
  client/src/components/categories/Categories.js
  client/src/components/landing-page/Landing.js
  package-lock.json
  package.json
Labels: approved

#50 added messge befor deleted and passed the user name to navbar compone…
  client/src/components/cart/Cart.js
  client/src/components/cartItem/CartItem.js
Labels: approved

#51 created the product page and styled both the navbar and product compo…
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/assets/logo.png
  client/src/components/landing-page/Landing.js
  client/src/components/navbar/Navbar.css
  client/src/components/navbar/Navbar.js
  client/src/components/product/Product.css
  client/src/components/product/Product.js
  server/database/config/productBuild.js
Labels: approved

#52 sent username for cart component
  server/controllers/products/getCartProducts.js
Labels: approved

#53 add the navbar component in cart if it is empty
  client/src/components/cart/Cart.js
Labels: approved

#55 deleted-message-been-in-if-statement
  client/src/components/cartItem/CartItem.js
Labels: for-review

#58 adding the pagination relates #57
  client/src/components/cardsContainer/CardsContainer.css
  client/src/components/categories/Categories.css
  client/src/components/landing-page/Landing.js
  client/src/components/landing-page/Pagination.js
Labels: approved

#60 styled the signup and signin components
  client/src/components/sign-in/Sign-in.css
  client/src/components/sign-in/Sign-in.js
  client/src/components/sign-up/Sign-up.css
  client/src/components/sign-up/Sign-up.js
Labels: approved

#62 Edit: name of the function in sign out JS file
  server/controllers/register/signOut.js
Labels: for-review

#63 fix: small bug in the landing page,
  client/src/components/cart/Cart.js
  client/src/components/cartItem/CartItem.js
  client/src/components/landing-page/Landing.js
Labels: for-review
